"""Type stubs for rvgsrust_xlsxwriter._core (the PyO3-compiled extension).

Hand-written from src/lib.rs, not auto-generated. Literal types list the
exact strings each setter accepts (lower-cased internally, so case is
not significant) -- these were read out of the `match` arms in lib.rs's
parse_*() helpers, not guessed or inferred from docs.

Two accepted-value validation styles exist in the underlying code and
are preserved here rather than papered over:

- Format.set_border() and friends raise ValueError on an unrecognised
  string.
- Format.set_align(), set_vertical_align() and set_pattern() do NOT
  raise on an unrecognised string; they silently fall back to a default
  (Left / VerticalCenter / None respectively). The Literal types below
  document the accepted values, but a type checker won't catch a typo
  passed as a plain str, and neither will the library at runtime.
"""

from __future__ import annotations
from typing import Literal, Optional, Union, Any, Iterable

BorderStyle = Literal["thin", "medium", "thick", "dashed", "dotted", "double", "hair"]
DiagonalBorderType = Literal["none", "up", "down", "up_down"]
Align = Literal["left", "center", "right", "fill", "justify", "center_across", "distributed"]
VerticalAlign = Literal["top", "vcenter", "center", "bottom", "vdistributed", "distributed", "vjustify", "justify"]
Pattern = Literal[
    "none", "solid", "medium_gray", "dark_gray", "light_gray",
    "dark_horizontal", "dark_vertical", "dark_down", "dark_up",
    "dark_grid", "dark_trellis", "light_horizontal", "light_vertical",
    "light_down", "light_up", "light_grid", "light_trellis",
    "gray_125", "gray_0625",
]
DashType = Literal[
    "solid", "round_dot", "square_dot", "dash", "dash_dot",
    "long_dash", "long_dash_dot", "long_dash_dot_dot",
]
ChartType = Literal[
    "area", "area_stacked", "area_percent_stacked",
    "bar", "bar_stacked", "bar_percent_stacked",
    "column", "column_stacked", "column_percent_stacked",
    "doughnut", "line", "line_stacked", "line_percent_stacked",
    "pie", "radar", "radar_with_markers", "radar_filled",
    "scatter", "scatter_straight", "scatter_straight_with_markers",
    "scatter_smooth", "scatter_smooth_with_markers", "stock",
]
MarkerType = Literal[
    "square", "diamond", "triangle", "x", "star",
    "short_dash", "long_dash", "circle", "plus_sign",
]
TrendlineType = Literal[
    "none", "linear", "exponential", "logarithmic",
    "power", "polynomial", "moving_average",
]
SparklineType = Literal["line", "column", "win_lose", "win_loss"]
LabelPosition = Literal[
    "default", "center", "right", "left", "above", "below",
    "inside_base", "inside_end", "outside_end", "best_fit",
]
LegendPosition = Literal["right", "left", "top", "bottom", "top_right"]
EmptyCells = Literal["gaps", "zero", "connected"]
BarDirection = Literal["context", "left_to_right", "right_to_left"]
BarAxisPosition = Literal["automatic", "midpoint", "none"]
TableStyle = str  # "none", "light1".."light21", "medium1".."medium28", "dark1".."dark11"
TableFunction = Literal[
    "none", "average", "count", "count_numbers", "max", "min",
    "sum", "stddev", "var",
]
# Union with plain str because set_total_function() treats any string
# that doesn't match one of the above (after lower-casing and stripping
# underscores) as a custom formula, rather than raising.
TableFunctionArg = Union[TableFunction, str]
CfRuleType = Literal["automatic", "lowest", "min", "highest", "max", "number", "percent", "percentile", "formula"]
IconSetType = Literal[
    "three_arrows", "three_arrows_gray", "three_flags", "three_traffic_lights",
    "three_traffic_lights_with_rim", "three_signs", "three_symbols_circled",
    "three_symbols", "three_stars", "three_triangles",
    "four_arrows", "four_arrows_gray", "four_red_to_black", "four_histograms",
    "four_traffic_lights",
    "five_arrows", "five_arrows_gray", "five_histograms", "five_quadrants", "five_boxes",
]
CfTopRule = Literal["top", "bottom", "top_percent", "bottom_percent"]
CfTextRule = Literal["contains", "does_not_contain", "begins_with", "ends_with"]
CfDateRule = Literal[
    "yesterday", "today", "tomorrow", "last_7_days",
    "last_week", "this_week", "next_week",
    "last_month", "this_month", "next_month",
]
CfAverageRule = Literal[
    "above", "below", "equal_or_above", "equal_or_below",
    "1_std_dev_above", "2_std_dev_above", "3_std_dev_above",
    "1_std_dev_below", "2_std_dev_below", "3_std_dev_below",
]

class Format:
    """Chainable cell format. Every setter returns self."""
    def set_bold(self) -> "Format": ...
    def set_italic(self) -> "Format": ...
    def set_underline(self) -> "Format": ...
    def set_font_strikethrough(self) -> "Format": ...
    def set_quote_prefix(self) -> "Format": ...
    def set_hyperlink(self) -> "Format": ...
    def set_checkbox(self) -> "Format": ...
    def set_font_family(self, font_family: int) -> "Format":
        """1=Roman, 2=Swiss, 3=Modern, 4=Script, 5=Decorative, 0=not applicable."""
        ...
    def set_font_charset(self, font_charset: int) -> "Format": ...
    def set_font_script(self, script: Literal["none", "superscript", "subscript"]) -> "Format": ...
    def set_reading_direction(self, reading_direction: int) -> "Format":
        """0=context-dependent, 1=left-to-right, 2=right-to-left.
        Raises ValueError outside that range."""
        ...
    def unset_bold(self) -> "Format": ...
    def unset_italic(self) -> "Format": ...
    def unset_font_strikethrough(self) -> "Format": ...
    def unset_text_wrap(self) -> "Format": ...
    def unset_shrink(self) -> "Format": ...
    def unset_hidden(self) -> "Format": ...
    def unset_quote_prefix(self) -> "Format": ...
    def unset_checkbox(self) -> "Format": ...
    def unset_hyperlink_style(self) -> "Format": ...
    def set_font_name(self, name: str) -> "Format": ...
    def set_font_size(self, size: float) -> "Format": ...
    def set_font_color(self, color: str) -> "Format": ...
    def set_background_color(self, color: str) -> "Format": ...
    def set_foreground_color(self, color: str) -> "Format": ...
    def set_pattern(self, pattern: Pattern) -> "Format":
        """Unrecognised strings silently fall back to 'none' -- no exception."""
        ...
    def set_border(self, border: BorderStyle) -> "Format":
        """Applies to all four sides. Raises ValueError if unrecognised."""
        ...
    def set_border_color(self, color: str) -> "Format": ...
    def set_top_border(self, border: BorderStyle) -> "Format": ...
    def set_bottom_border(self, border: BorderStyle) -> "Format": ...
    def set_left_border(self, border: BorderStyle) -> "Format": ...
    def set_right_border(self, border: BorderStyle) -> "Format": ...
    def set_border_top_color(self, color: str) -> "Format": ...
    def set_border_bottom_color(self, color: str) -> "Format": ...
    def set_border_left_color(self, color: str) -> "Format": ...
    def set_border_right_color(self, color: str) -> "Format": ...
    def set_border_diagonal(self, border: BorderStyle) -> "Format": ...
    def set_border_diagonal_color(self, color: str) -> "Format": ...
    def set_border_diagonal_type(self, border_type: DiagonalBorderType) -> "Format": ...
    def set_align(self, align: Align) -> "Format":
        """Unrecognised strings silently fall back to 'left' -- no exception."""
        ...
    def set_vertical_align(self, align: VerticalAlign) -> "Format":
        """Unrecognised strings silently fall back to 'vcenter' -- no exception."""
        ...
    def set_text_wrap(self) -> "Format": ...
    def set_rotation(self, rotation: int) -> "Format": ...
    def set_indent(self, indent: int) -> "Format": ...
    def set_shrink(self) -> "Format": ...
    def set_num_format(self, format: str) -> "Format": ...
    def set_locked(self) -> "Format": ...
    def set_unlocked(self) -> "Format": ...
    def set_hidden(self) -> "Format": ...

class Workbook:
    """Workbook with context manager support.

    Wraps the core Rust-backed Workbook to add __enter__ / __exit__.
    """
    path: Optional[str]
    def __init__(self, path: Optional[str] = None) -> None: ...
    def __enter__(self) -> "Workbook": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def add_worksheet(self, name: Optional[str] = None, constant_memory: bool = False) -> "Worksheet": ...
    def add_chartsheet(self) -> "Worksheet":
        """Returns the same Worksheet type as add_worksheet() -- a
        chartsheet is a worksheet consisting of only a single chart.
        Auto-named "Chart1", "Chart2", ...; rename with set_name()."""
        ...
    def add_format(self) -> Format: ...
    def define_name(self, name: str, formula: str) -> None: ...
    def use_excel_2023_theme(self) -> None: ...
    def use_custom_theme(self, path: str) -> None: ...
    def set_default_format(self, format: "Format", row_height: int, col_width: int) -> None: ...
    def add_vba_project(self, path: str) -> None: ...
    def set_vba_name(self, name: str) -> None: ...
    def read_only_recommended(self) -> None: ...
    def set_tempdir(self, path: str) -> None: ...
    def use_zip_large_file(self, enable: bool) -> None: ...
    def set_properties(
        self,
        title: Optional[str] = None,
        author: Optional[str] = None,
        subject: Optional[str] = None,
        keywords: Optional[str] = None,
        comments: Optional[str] = None,
    ) -> None: ...
    def close(self, path: Optional[str] = None) -> None:
        """Save and close. Uses the constructor path when `path` is omitted."""
        ...
    def save_to_buffer(self) -> bytes:
        """Serialize the workbook to bytes instead of writing a path --
        useful for a web response or streaming, with no temp-file
        round trip. Same cost as close()/save(), and the GIL is
        released for it the same way. Can be called more than once or
        alongside close(); this binding places no restriction on that.
        """
        ...

IgnoreErrorType = Literal[
    "number_stored_as_text",
    "formula_error",
    "formula_differs",
    "formula_refers_to_empty_cells",
    "formula_omits_cells",
    "data_validation_error",
    "two_digit_text_year",
    "unlocked_cells_with_formula",
    "inconsistent_column_formula",
]

HeaderImagePosition = Literal["left", "center", "right"]

class Worksheet:
    def write(self, row: int, col: int, value: Any, format: Optional[Format] = None) -> None: ...
    def write_row(self, row: int, col: int, values: Iterable[Any], format: Optional[Format] = None) -> None: ...
    def write_column(self, row: int, col: int, values: Iterable[Any], format: Optional[Format] = None) -> None: ...
    def write_rows(
        self, start_row: int, start_col: int, rows: Iterable[Iterable[Any]],
        format: Optional[Format] = None, header_format: Optional[Format] = None,
        write_header: bool = False,
    ) -> None: ...
    def write_records(
        self, start_row: int, start_col: int, records: Iterable[dict],
        headers: Optional[list[str]] = None, format: Optional[Format] = None,
        header_format: Optional[Format] = None, write_header: bool = True,
    ) -> None: ...
    def write_dataframe(
        self, start_row: int, start_col: int, data: Any,
        header_format: Optional[Format] = None, write_header: bool = True,
        column_formats: Optional[dict[str, Format]] = None,
    ) -> None:
        """Zero-copy Arrow path. `data` must expose __arrow_c_stream__
        (pandas 2.x+, polars via .to_arrow(), pyarrow.Table/RecordBatchReader).

        column_formats merges a per-column format into every cell as
        it's written, keyed by column name. This is a true per-cell
        merge, not a column-scoped format applied afterward: a border
        given here survives on a date/datetime column alongside that
        column's own date number format, because both land in the same
        cellXf rather than the column-level format losing to the cell's
        own format under OOXML precedence. Raises ValueError if a key
        doesn't match any column name, before any row is written.

        Null values are always skipped -- never written as a formatted
        blank cell -- regardless of whether their column has a
        column_formats entry or an automatic date/datetime format. A
        null stays a genuinely absent value, not a styled empty cell.
        (Contrast with write()/write_row()/etc, where an explicit
        None paired with a format IS written as a formatted blank
        cell -- that's a different, deliberate API for a different use
        case: an intentionally empty-but-styled cell versus an absent
        dataframe value.)
        """
        ...
    def write_formula(self, row: int, col: int, formula: str, format: Optional[Format] = None) -> None: ...
    def write_url(
        self, row: int, col: int, url: str, format: Optional[Format] = None,
        text: Optional[str] = None, tip: Optional[str] = None,
    ) -> None: ...
    def write_date(self, row: int, col: int, year: int, month: int, day: int, format: Optional[Format] = None) -> None: ...
    def write_date_py(self, row: int, col: int, date: Any, format: Optional[Format] = None) -> None: ...
    def write_datetime(
        self, row: int, col: int, year: int, month: int, day: int,
        hour: int = 0, min: int = 0, sec: int = 0, format: Optional[Format] = None,
    ) -> None: ...
    def write_datetime_py(self, row: int, col: int, dt: Any, format: Optional[Format] = None) -> None: ...
    def write_rich_string(self, row: int, col: int, parts: list, format: Optional[Format] = None) -> None: ...
    def merge_range(self, first_row: int, first_col: int, last_row: int, last_col: int, value: Any, format: Optional[Format] = None) -> None: ...
    def insert_image(self, row: int, col: int, image_path: str) -> None: ...
    def insert_image_with_offset(
        self, row: int, col: int, image_path: str, x_offset: int, y_offset: int
    ) -> None: ...
    def embed_image(self, row: int, col: int, image_path: str) -> None: ...
    def embed_image_with_format(
        self, row: int, col: int, image_path: str, format: "Format"
    ) -> None: ...
    def insert_image_fit_to_cell(
        self, row: int, col: int, image_path: str, keep_aspect_ratio: bool = True
    ) -> None: ...
    def insert_image_fit_to_cell_centered(
        self, row: int, col: int, image_path: str
    ) -> None: ...
    def insert_background_image(self, image_path: str) -> None: ...
    def insert_checkbox(
        self, row: int, col: int, value: bool, format: Optional["Format"] = None
    ) -> None: ...
    def insert_button(self, row: int, col: int, button: "Button") -> None: ...
    def insert_button_with_offset(
        self, row: int, col: int, button: "Button", x_offset: int, y_offset: int
    ) -> None: ...
    def insert_shape(self, row: int, col: int, shape: "Shape") -> None: ...
    def insert_shape_with_offset(
        self, row: int, col: int, shape: "Shape", x_offset: int, y_offset: int
    ) -> None: ...
    def insert_note(self, row: int, col: int, note: "Note") -> None: ...
    def show_all_notes(self, enable: bool) -> None: ...
    def set_default_note_author(self, name: str) -> None: ...
    def filter_column(self, col: int, filter_condition: "FilterCondition") -> None: ...
    def set_vba_name(self, name: str) -> None: ...
    def insert_chart(self, row: int, col: int, chart: "Chart", x_offset: int = 0, y_offset: int = 0) -> None: ...
    def add_table(self, first_row: int, first_col: int, last_row: int, last_col: int, table: "Table") -> None: ...
    def add_conditional_format(self, first_row: int, first_col: int, last_row: int, last_col: int, cf: Any) -> None: ...
    def add_data_validation(self, first_row: int, first_col: int, last_row: int, last_col: int, validation: DataValidation) -> None: ...
    def add_sparkline(self, row: int, col: int, sparkline: "Sparkline") -> None: ...
    def add_sparkline_group(self, first_row: int, first_col: int, last_row: int, last_col: int, sparkline: "Sparkline") -> None: ...
    def set_column_width(self, col: int, width: float) -> None: ...
    def set_column_format(self, col: int, format: Format) -> None: ...
    def set_column_range_format(self, first_col: int, last_col: int, format: Format) -> None: ...
    def set_row_height(self, row: int, height: float) -> None: ...
    def set_row_format(self, row: int, format: Format) -> None: ...
    def set_cell_format(self, row: int, col: int, format: Format) -> None: ...
    def set_range_format(self, first_row: int, first_col: int, last_row: int, last_col: int, format: Format) -> None: ...
    def set_range_format_with_border(
        self, first_row: int, first_col: int, last_row: int, last_col: int,
        cell_format: Format, border_format: Format,
    ) -> None:
        """Like set_range_format(), plus a border built around the outside
        of the range -- up to 9 per-cell format combinations handled
        internally instead of by the caller."""
        ...
    def clear_cell_format(self, row: int, col: int) -> None:
        """Clears a cell's format, leaving its value untouched. A no-op
        on an unformatted or nonexistent cell, not an error."""
        ...
    def clear_cell(self, row: int, col: int) -> None:
        """Clears both a cell's value and its format."""
        ...
    def set_row_hidden(self, row: int) -> None: ...
    def set_row_unhidden(self, row: int) -> None: ...
    def set_column_hidden(self, col: int) -> None: ...
    def hide_unused_rows(self, enable: bool) -> None: ...
    def set_row_height_pixels(self, row: int, height: int) -> None: ...
    def set_column_width_pixels(self, col: int, width: int) -> None: ...
    def set_default_row_height(self, height: float) -> None: ...
    def set_zoom(self, zoom: int) -> None: ...
    def set_selection(self, first_row: int, first_col: int, last_row: int, last_col: int) -> None: ...
    def set_top_left_cell(self, row: int, col: int) -> None: ...
    def set_active(self, enable: bool) -> None: ...
    def set_first_tab(self, enable: bool) -> None: ...
    def set_right_to_left(self, enable: bool) -> None: ...
    def set_view_normal(self) -> None: ...
    def set_view_page_layout(self) -> None: ...
    def set_view_page_break_preview(self) -> None: ...
    def ignore_error(self, row: int, col: int, error_type: IgnoreErrorType) -> None: ...
    def ignore_error_range(
        self, first_row: int, first_col: int, last_row: int, last_col: int,
        error_type: IgnoreErrorType,
    ) -> None: ...
    def set_autofit_max_width(self, max_width: int) -> None: ...
    def set_autofit_max_row(self, max_row: int) -> None: ...
    def set_nan_value(self, value: str) -> None: ...
    def set_infinity_value(self, value: str) -> None: ...
    def set_neg_infinity_value(self, value: str) -> None: ...
    def freeze_panes(self, row: int, col: int) -> None: ...
    def group_rows(self, first_row: int, last_row: int) -> None: ...
    def group_rows_collapsed(self, first_row: int, last_row: int) -> None:
        """The row after last_row becomes the summary/toggle row."""
        ...
    def group_columns(self, first_col: int, last_col: int) -> None: ...
    def group_columns_collapsed(self, first_col: int, last_col: int) -> None:
        """The column after last_col becomes the summary/toggle column."""
        ...
    def group_symbols_above(self, enable: bool) -> None:
        """Worksheet-level display setting, affects every group_rows() on the sheet."""
        ...
    def group_symbols_to_left(self, enable: bool) -> None:
        """Worksheet-level display setting, affects every group_columns() on the sheet."""
        ...
    def autofit(self) -> None: ...
    def autofilter(self, first_row: int, first_col: int, last_row: int, last_col: int) -> None: ...
    def hide(self) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_tab_color(self, color: str) -> None: ...
    def set_header(self, text: str) -> None:
        """Not validated here. Use &L/&C/&R to align text to the
        left/center/right section. &[Page]/&[Pages]/&[Tab] placeholders
        work but are normalized by rust_xlsxwriter to the older
        single-letter codes (&P/&N/&A respectively) before writing --
        both forms are valid Excel codes and render identically, this
        crate just doesn't preserve which spelling was given. Excel's
        256-character limit (including control characters) on the
        combined string isn't checked at write time; an oversized
        string is silently truncated when Excel opens the file.
        See https://rustxlsxwriter.github.io/worksheet/headers.html
        """
        ...
    def set_footer(self, text: str) -> None:
        """Same syntax and caveats as set_header()."""
        ...
    def set_header_image(
        self, image_path: str, position: HeaderImagePosition
    ) -> None:
        """Requires a matching &[Picture]/&[G] placeholder already present
        in the header text set via set_header()."""
        ...
    def set_footer_image(
        self, image_path: str, position: HeaderImagePosition
    ) -> None:
        """Requires a matching &[Picture]/&[G] placeholder already present
        in the footer text set via set_footer()."""
        ...
    def set_header_footer_scale_with_doc(self, enable: bool) -> None: ...
    def set_header_footer_align_with_page(self, enable: bool) -> None: ...
    def protect(self, password: Optional[str] = None) -> None: ...
    def protect_with_options(
        self, options: "ProtectionOptions", password: Optional[str] = None
    ) -> None: ...
    def unprotect_range(
        self, first_row: int, first_col: int, last_row: int, last_col: int,
        name: str = "", password: str = "",
    ) -> None: ...
    def set_landscape(self) -> None: ...
    def set_portrait(self) -> None: ...
    def set_paper_size(self, paper_size: int) -> None: ...
    def set_page_order(self, enable: bool) -> None: ...
    def set_margins(
        self, left: float = 0.7, right: float = 0.7, top: float = 0.75,
        bottom: float = 0.75, header: float = 0.3, footer: float = 0.3,
    ) -> None: ...
    def set_print_area(self, first_row: int, first_col: int, last_row: int, last_col: int) -> None: ...
    def set_repeat_rows(self, first_row: int, last_row: int) -> None: ...
    def set_repeat_columns(self, first_col: int, last_col: int) -> None: ...
    def set_print_fit_to_pages(self, width: int, height: int) -> None: ...
    def set_print_scale(self, scale: int) -> None: ...
    def set_page_breaks(self, breaks: list[int]) -> None: ...
    def set_vertical_page_breaks(self, breaks: list[int]) -> None: ...
    def set_print_gridlines(self, enable: bool) -> None: ...
    def set_print_headings(self, enable: bool) -> None: ...
    def set_print_center_horizontally(self, enable: bool) -> None: ...
    def set_print_center_vertically(self, enable: bool) -> None: ...
    def set_print_black_and_white(self, enable: bool) -> None: ...
    def set_print_draft(self, enable: bool) -> None: ...
    def set_print_first_page_number(self, page_number: int) -> None: ...

class Table:
    def set_columns(self, columns: list["TableColumn"]) -> "Table": ...
    def set_name(self, name: str) -> "Table": ...
    def set_style(self, style: TableStyle) -> "Table": ...
    def set_total_row(self, enable: bool) -> "Table": ...
    def set_banded_rows(self, enable: bool) -> "Table": ...
    def set_banded_columns(self, enable: bool) -> "Table": ...
    def set_header_row(self, enable: bool) -> "Table": ...
    def set_first_column(self, enable: bool) -> "Table": ...
    def set_last_column(self, enable: bool) -> "Table": ...
    def set_autofilter(self, enable: bool) -> "Table": ...
    def set_alt_text(self, alt_text: str) -> "Table": ...
    def set_alt_text_title(self, title: str) -> "Table": ...
    def has_header_row(self) -> bool: ...
    def has_total_row(self) -> bool: ...

class TableColumn:
    def set_header(self, caption: str) -> "TableColumn": ...
    def set_header_format(self, format: Format) -> "TableColumn": ...
    def set_format(self, format: Format) -> "TableColumn": ...
    def set_formula(self, formula: str) -> "TableColumn": ...
    def set_total_function(self, function: TableFunctionArg) -> "TableColumn":
        """Any string not matching TableFunction is treated as a custom
        formula name rather than raising."""
        ...
    def set_total_label(self, label: str) -> "TableColumn": ...

class Sparkline:
    def set_range(self, range: str) -> "Sparkline": ...
    def set_type(self, sparkline_type: SparklineType) -> "Sparkline": ...
    def set_style(self, style: int) -> "Sparkline": ...
    def set_sparkline_color(self, color: str) -> "Sparkline": ...
    def set_high_point_color(self, color: str) -> "Sparkline": ...
    def set_low_point_color(self, color: str) -> "Sparkline": ...
    def set_first_point_color(self, color: str) -> "Sparkline": ...
    def set_last_point_color(self, color: str) -> "Sparkline": ...
    def set_negative_points_color(self, color: str) -> "Sparkline": ...
    def set_markers_color(self, color: str) -> "Sparkline": ...
    def show_high_point(self, enable: bool) -> "Sparkline": ...
    def show_low_point(self, enable: bool) -> "Sparkline": ...
    def show_first_point(self, enable: bool) -> "Sparkline": ...
    def show_last_point(self, enable: bool) -> "Sparkline": ...
    def show_negative_points(self, enable: bool) -> "Sparkline": ...
    def show_markers(self, enable: bool) -> "Sparkline": ...
    def show_axis(self, enable: bool) -> "Sparkline": ...
    def show_hidden_data(self, enable: bool) -> "Sparkline": ...
    def show_empty_cells_as(self, option: EmptyCells) -> "Sparkline": ...
    def set_line_weight(self, weight: float) -> "Sparkline": ...
    def set_custom_max(self, max: float) -> "Sparkline": ...
    def set_custom_min(self, min: float) -> "Sparkline": ...
    def set_group_max(self, enable: bool) -> "Sparkline": ...
    def set_group_min(self, enable: bool) -> "Sparkline": ...
    def set_date_range(self, range: str) -> "Sparkline": ...
    def set_right_to_left(self, enable: bool) -> "Sparkline": ...
    def set_column_order(self, enable: bool) -> "Sparkline": ...

class Chart:
    def __init__(self, chart_type: ChartType) -> None: ...
    def push_series(self, series: "ChartSeries") -> "Chart": ...
    def set_title_name(self, name: str) -> "Chart": ...
    def set_title_hidden(self) -> "Chart": ...
    def set_title_overlay(self, enable: bool) -> "Chart": ...
    def set_title_font(self, font: "ChartFont") -> "Chart": ...
    def set_title_format(self, format: "ChartFormat") -> "Chart": ...
    def set_up_down_bars(self, enable: bool) -> "Chart": ...
    def set_up_bar_format(self, format: "ChartFormat") -> "Chart": ...
    def set_down_bar_format(self, format: "ChartFormat") -> "Chart": ...
    def set_high_low_lines(self, enable: bool) -> "Chart": ...
    def set_high_low_lines_format(self, format: "ChartFormat") -> "Chart": ...
    def set_drop_lines(self, enable: bool) -> "Chart": ...
    def set_drop_lines_format(self, format: "ChartFormat") -> "Chart": ...
    def set_chart_area_format(self, format: "ChartFormat") -> "Chart": ...
    def set_plot_area_format(self, format: "ChartFormat") -> "Chart": ...
    def combine(self, other: "Chart") -> "Chart":
        """Combines this chart's primary type with a secondary chart type.
        Upstream clones `other` internally; later mutations to it have no
        effect here."""
        ...
    def set_legend_position(self, position: LegendPosition) -> "Chart": ...
    def set_legend_hidden(self) -> "Chart": ...
    def set_legend_overlay(self, enable: bool) -> "Chart": ...
    def set_legend_font(self, font: "ChartFont") -> "Chart": ...
    def set_legend_format(self, format: "ChartFormat") -> "Chart": ...
    def set_x_axis_name(self, name: str) -> "Chart": ...
    def set_y_axis_name(self, name: str) -> "Chart": ...
    def set_x_axis_min(self, min: float) -> "Chart": ...
    def set_x_axis_max(self, max: float) -> "Chart": ...
    def set_y_axis_min(self, min: float) -> "Chart": ...
    def set_y_axis_max(self, max: float) -> "Chart": ...
    def set_width(self, width: float) -> "Chart": ...
    def set_height(self, height: float) -> "Chart": ...
    def set_style(self, style: int) -> "Chart": ...
    def set_hole_size(self, hole_size: int) -> "Chart": ...
    def set_alt_text(self, alt_text: str) -> "Chart": ...
    def set_name(self, name: str) -> "Chart": ...
    def set_rotation(self, rotation: int) -> "Chart": ...
    def show_hidden_data(self) -> "Chart": ...
    def show_na_as_empty_cell(self) -> "Chart": ...
    def show_empty_cells_as(self, option: EmptyCells) -> "Chart": ...
    # set_x_axis_*/set_y_axis_* (name/min/max/major_unit/minor_unit/log_base/
    # num_format/hidden/reverse/major_gridlines/minor_gridlines/font/format;
    # date_axis/text_axis are x-only) mirror each other and are omitted here
    # for brevity -- see README.md's Charts section for the full list.
    # set_x2_axis_*/set_y2_axis_* mirror the primary axis methods above
    # (same name/min/max/... set, date_axis/text_axis still x-only) and
    # only take effect when a series has set_secondary_axis(True).

class ChartSeries:
    def set_values(self, range: str) -> "ChartSeries": ...
    def set_categories(self, range: str) -> "ChartSeries": ...
    def set_name(self, name: str) -> "ChartSeries": ...
    def set_format(self, format: "ChartFormat") -> "ChartSeries": ...
    def set_marker(self, marker: "ChartMarker") -> "ChartSeries": ...
    def set_trendline(self, trendline: "ChartTrendline") -> "ChartSeries": ...
    def set_data_label(self, data_label: "ChartDataLabel") -> "ChartSeries": ...
    def set_custom_data_labels(self, labels: list) -> "ChartSeries": ...
    def set_secondary_axis(self, enable: bool) -> "ChartSeries": ...
    def set_overlap(self, overlap: int) -> "ChartSeries": ...
    def set_gap(self, gap: int) -> "ChartSeries": ...
    def set_smooth(self, enable: bool) -> "ChartSeries": ...
    def set_invert_if_negative(self, enable: bool) -> "ChartSeries": ...
    def set_invert_if_negative_color(self, color: str) -> "ChartSeries": ...
    def set_point_colors(self, colors: list[str]) -> "ChartSeries": ...
    def delete_from_legend(self, enable: bool) -> "ChartSeries": ...
    def set_y_error_bars(self, error_bars: "ChartErrorBars") -> "ChartSeries": ...
    def set_x_error_bars(self, error_bars: "ChartErrorBars") -> "ChartSeries": ...

ErrorBarsDirection = Literal["both", "minus", "plus"]

class ChartErrorBars:
    def __init__(self) -> None: ...
    def set_type_standard_error(self) -> "ChartErrorBars": ...
    def set_type_fixed_value(self, value: float) -> "ChartErrorBars": ...
    def set_type_percentage(self, value: float) -> "ChartErrorBars": ...
    def set_type_standard_deviation(self, value: float) -> "ChartErrorBars": ...
    def set_type_custom(self, plus_range: str, minus_range: str) -> "ChartErrorBars": ...
    def set_direction(self, direction: ErrorBarsDirection) -> "ChartErrorBars": ...
    def set_end_cap(self, enable: bool) -> "ChartErrorBars": ...
    def set_format(self, format: "ChartFormat") -> "ChartErrorBars": ...

class ChartFormat:
    def set_fill_color(self, color: str) -> "ChartFormat": ...
    def set_fill_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_no_fill(self) -> "ChartFormat": ...
    def set_line_color(self, color: str) -> "ChartFormat": ...
    def set_line_width(self, width: float) -> "ChartFormat": ...
    def set_line_dash_type(self, dash_type: DashType) -> "ChartFormat": ...
    def set_line_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_line_hidden(self, enable: bool) -> "ChartFormat": ...
    def set_no_line(self) -> "ChartFormat": ...
    def set_border_color(self, color: str) -> "ChartFormat": ...
    def set_border_width(self, width: float) -> "ChartFormat": ...
    def set_border_dash_type(self, dash_type: DashType) -> "ChartFormat": ...
    def set_border_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_border_hidden(self, enable: bool) -> "ChartFormat": ...
    def set_no_border(self) -> "ChartFormat": ...

class ChartFont:
    def set_bold(self) -> "ChartFont": ...
    def unset_bold(self) -> "ChartFont": ...
    def set_default_bold(self, enable: bool) -> "ChartFont": ...
    def set_italic(self) -> "ChartFont": ...
    def set_underline(self) -> "ChartFont": ...
    def set_strikethrough(self) -> "ChartFont": ...
    def set_color(self, color: str) -> "ChartFont": ...
    def set_name(self, font_name: str) -> "ChartFont": ...
    def set_size(self, font_size: float) -> "ChartFont": ...
    def set_rotation(self, rotation: int) -> "ChartFont": ...
    def set_right_to_left(self, enable: bool) -> "ChartFont": ...
    def set_pitch_family(self, family: int) -> "ChartFont": ...
    def set_character_set(self, character_set: int) -> "ChartFont": ...

class ChartMarker:
    def set_type(self, marker_type: MarkerType) -> "ChartMarker": ...
    def set_automatic(self) -> "ChartMarker": ...
    def set_none(self) -> "ChartMarker": ...
    def set_size(self, size: int) -> "ChartMarker": ...
    def set_format(self, format: ChartFormat) -> "ChartMarker": ...

class ChartTrendline:
    def set_type(self, trend_type: TrendlineType, period: int = 2) -> "ChartTrendline": ...
    def set_forward_period(self, period: float) -> "ChartTrendline": ...
    def set_backward_period(self, period: float) -> "ChartTrendline": ...
    def set_intercept(self, intercept: float) -> "ChartTrendline": ...
    def set_display_equation(self, enable: bool) -> "ChartTrendline": ...
    def set_display_r_squared(self, enable: bool) -> "ChartTrendline": ...
    def set_name(self, name: str) -> "ChartTrendline": ...
    def set_format(self, format: ChartFormat) -> "ChartTrendline": ...
    def set_label_font(self, font: ChartFont) -> "ChartTrendline": ...
    def set_label_format(self, format: ChartFormat) -> "ChartTrendline": ...
    def delete_from_legend(self, enable: bool) -> "ChartTrendline": ...

class ChartDataLabel:
    def show_value(self) -> "ChartDataLabel": ...
    def show_category_name(self) -> "ChartDataLabel": ...
    def show_series_name(self) -> "ChartDataLabel": ...
    def show_percentage(self) -> "ChartDataLabel": ...
    def show_leader_lines(self) -> "ChartDataLabel": ...
    def show_legend_key(self) -> "ChartDataLabel": ...
    def show_x_value(self) -> "ChartDataLabel": ...
    def show_y_value(self) -> "ChartDataLabel": ...
    def set_hidden(self, enable: bool) -> "ChartDataLabel": ...
    def set_position(self, position: LabelPosition) -> "ChartDataLabel": ...
    def set_num_format(self, num_format: str) -> "ChartDataLabel": ...
    def set_separator(self, separator: str) -> "ChartDataLabel": ...
    def set_value(self, value: str) -> "ChartDataLabel": ...
    def set_font(self, font: ChartFont) -> "ChartDataLabel": ...
    def set_format(self, format: ChartFormat) -> "ChartDataLabel": ...
    def set_custom(self, enable: bool) -> "ChartDataLabel": ...

DVRuleType = Literal[
    "equal_to", "not_equal_to", "greater_than", "greater_than_or_equal_to",
    "less_than", "less_than_or_equal_to", "between", "not_between",
]
DVErrorStyle = Literal["stop", "warning", "information"]

class ProtectionOptions:
    def __init__(
        self,
        select_locked_cells: bool = True,
        select_unlocked_cells: bool = True,
        format_cells: bool = False,
        format_columns: bool = False,
        format_rows: bool = False,
        insert_columns: bool = False,
        insert_rows: bool = False,
        insert_links: bool = False,
        delete_columns: bool = False,
        delete_rows: bool = False,
        sort: bool = False,
        use_autofilter: bool = False,
        use_pivot_tables: bool = False,
        edit_scenarios: bool = False,
        edit_objects: bool = False,
        contents: bool = True,
    ) -> None: ...

class Button:
    def __init__(self) -> None: ...
    def set_caption(self, caption: str) -> None: ...
    def set_macro(self, name: str) -> None: ...
    def set_width(self, width: int) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_alt_text(self, alt_text: str) -> None: ...

class Shape:
    """Only Excel's Textbox shape type is supported (upstream doesn't
    implement any other shape type). Only plain text/sizing is exposed --
    not fill, line, font, or text direction/rotation."""
    @staticmethod
    def textbox() -> "Shape": ...
    def set_text(self, text: str) -> None: ...
    def set_width(self, width: int) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_alt_text(self, alt_text: str) -> None: ...

class Note:
    def __init__(self, text: str) -> None: ...
    def set_author(self, name: str) -> None: ...
    def set_width(self, width: int) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_visible(self, enable: bool) -> None: ...
    def set_alt_text(self, alt_text: str) -> None: ...
    def set_background_color(self, color: str) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, font_size: float) -> None: ...

FilterCriteriaType = Literal[
    "equal_to", "not_equal_to", "greater_than", "greater_than_or_equal_to",
    "less_than", "less_than_or_equal_to", "begins_with", "does_not_begin_with",
    "ends_with", "does_not_end_with", "contains", "does_not_contain",
]

class FilterCondition:
    def __init__(self) -> None: ...
    def add_list_filter(self, value: Union[float, str]) -> None: ...
    def add_list_blanks_filter(self) -> None: ...
    def add_custom_filter(
        self, criteria: FilterCriteriaType, value: Union[float, str]
    ) -> None: ...
    def add_custom_boolean_or(self) -> None:
        """Combines two add_custom_filter() calls with OR instead of the
        default AND."""
        ...

class DataValidation:
    """Not the full upstream surface: allow_date()/allow_time() and the
    allow_*_formula() cell-reference variants aren't implemented yet.
    Everything else -- including dropdown lists, the most-requested
    piece -- is.
    """
    def allow_whole_number(self, rule_type: DVRuleType, value: int, value2: Optional[int] = None) -> None:
        """value2 required for 'between'/'not_between', ignored otherwise."""
        ...
    def allow_decimal_number(self, rule_type: DVRuleType, value: float, value2: Optional[float] = None) -> None: ...
    def allow_text_length(self, rule_type: DVRuleType, value: int, value2: Optional[int] = None) -> None: ...
    def allow_list_strings(self, list: list[str]) -> None:
        """Raises ValueError if the strings joined with commas exceed
        Excel's 255-character limit."""
        ...
    def allow_list_formula(self, formula: str) -> None:
        """Dropdown sourced from a cell range, e.g. 'F2:F4'. No 255-char
        limit since the list isn't embedded in the rule."""
        ...
    def allow_custom(self, formula: str) -> None: ...
    def allow_date(
        self, rule_type: DVRuleType, value: Any, value2: Optional[Any] = None
    ) -> None:
        """value/value2 are Python date or datetime objects (only
        year/month/day are read)."""
        ...
    def allow_time(
        self, rule_type: DVRuleType, value: Any, value2: Optional[Any] = None
    ) -> None:
        """value/value2 are Python time or datetime objects (only
        hour/minute/second/microsecond are read)."""
        ...
    def allow_date_formula(
        self, rule_type: DVRuleType, formula: str, formula2: Optional[str] = None
    ) -> None: ...
    def allow_time_formula(
        self, rule_type: DVRuleType, formula: str, formula2: Optional[str] = None
    ) -> None: ...
    def allow_any_value(self) -> None:
        """Clears any rule from a previous allow_*() call."""
        ...
    def ignore_blank(self, enable: bool) -> None: ...
    def show_dropdown(self, enable: bool) -> None:
        """Only affects list-type validations."""
        ...
    def show_input_message(self, enable: bool) -> None: ...
    def set_input_title(self, text: str) -> None:
        """Max 32 characters."""
        ...
    def set_input_message(self, text: str) -> None:
        """Max 255 characters, newlines allowed."""
        ...
    def show_error_message(self, enable: bool) -> None: ...
    def set_error_title(self, text: str) -> None:
        """Max 32 characters."""
        ...
    def set_error_message(self, text: str) -> None:
        """Max 255 characters."""
        ...
    def set_error_style(self, style: DVErrorStyle) -> None: ...
    def set_multi_range(self, range: str) -> None:
        """Replaces the range given to add_data_validation() entirely
        with a set of non-contiguous cells, e.g. 'A1:A10,C1:C10' --
        include every range you want validated in this one call."""
        ...

class ConditionalFormatCell:
    def set_rule_greater_than(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_less_than(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_not_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_greater_than_or_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_less_than_or_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_between(self, minimum: Union[int, float], maximum: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_not_between(self, minimum: Union[int, float], maximum: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_format(self, format: Format) -> "ConditionalFormatCell": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatCell": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatCell": ...

class ConditionalFormatBlank:
    def invert(self) -> "ConditionalFormatBlank": ...
    def set_format(self, format: Format) -> "ConditionalFormatBlank": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatBlank": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatBlank": ...

class ConditionalFormatDuplicate:
    def invert(self) -> "ConditionalFormatDuplicate": ...
    def set_format(self, format: Format) -> "ConditionalFormatDuplicate": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDuplicate": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDuplicate": ...

class ConditionalFormatError:
    def invert(self) -> "ConditionalFormatError": ...
    def set_format(self, format: Format) -> "ConditionalFormatError": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatError": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatError": ...

class ConditionalFormatFormula:
    def set_rule(self, formula: str) -> "ConditionalFormatFormula": ...
    def set_format(self, format: Format) -> "ConditionalFormatFormula": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatFormula": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatFormula": ...

class ConditionalFormatAverage:
    def set_rule(self, rule: CfAverageRule) -> "ConditionalFormatAverage": ...
    def set_format(self, format: Format) -> "ConditionalFormatAverage": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatAverage": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatAverage": ...

class ConditionalFormatTop:
    def set_rule(self, kind: CfTopRule, value: int) -> "ConditionalFormatTop": ...
    def set_format(self, format: Format) -> "ConditionalFormatTop": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatTop": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatTop": ...

class ConditionalFormatText:
    def set_rule(self, kind: CfTextRule, text: str) -> "ConditionalFormatText": ...
    def set_format(self, format: Format) -> "ConditionalFormatText": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatText": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatText": ...

class ConditionalFormatDate:
    def set_rule(self, rule: CfDateRule) -> "ConditionalFormatDate": ...
    def set_format(self, format: Format) -> "ConditionalFormatDate": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDate": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDate": ...

class ConditionalFormat2ColorScale:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat2ColorScale": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat2ColorScale": ...
    def set_minimum_color(self, color: str) -> "ConditionalFormat2ColorScale": ...
    def set_maximum_color(self, color: str) -> "ConditionalFormat2ColorScale": ...
    def set_multi_range(self, range: str) -> "ConditionalFormat2ColorScale": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormat2ColorScale": ...

class ConditionalFormat3ColorScale:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_midpoint(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_minimum_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_midpoint_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_maximum_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_multi_range(self, range: str) -> "ConditionalFormat3ColorScale": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormat3ColorScale": ...

class ConditionalFormatDataBar:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormatDataBar": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormatDataBar": ...
    def set_fill_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_border_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_negative_fill_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_negative_border_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_axis_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_axis_position(self, position: BarAxisPosition) -> "ConditionalFormatDataBar": ...
    def set_solid_fill(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_border_off(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_bar_only(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_direction(self, direction: BarDirection) -> "ConditionalFormatDataBar": ...
    def use_classic_style(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDataBar": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDataBar": ...

class ConditionalFormatCustomIcon:
    """Overrides one icon/threshold within a ConditionalFormatIconSet.
    No set_format() -- Excel renders icon sets from the icon/threshold
    definitions themselves, same as color scales and data bars."""
    def set_rule(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormatCustomIcon":
        """rule_type='highest' is silently ignored (upstream: 'The highest
        option cannot be set for the minimum'). percent/percentile values
        outside 0-100 are also silently ignored, not rejected -- neither
        raises here since upstream doesn't treat them as errors either."""
        ...
    def set_icon_type(self, icon_type: IconSetType, index: int) -> "ConditionalFormatCustomIcon":
        """index must be within range for icon_type (0-2 for a 3-icon
        set, 0-3 for 4-icon, 0-4 for 5-icon) or this raises ValueError."""
        ...
    def set_no_icon(self, enable: bool) -> "ConditionalFormatCustomIcon": ...
    def set_greater_than(self, enable: bool) -> "ConditionalFormatCustomIcon": ...

class ConditionalFormatIconSet:
    """The constructor already calls set_icon_type("three_traffic_lights")
    internally, so a freshly-constructed instance is valid on its own
    without calling any method -- rust_xlsxwriter's own default
    construction doesn't populate the required per-icon rules, which
    would otherwise raise a validation error even with every setting
    left at its default."""
    def set_icon_type(self, icon_type: IconSetType) -> "ConditionalFormatIconSet":
        """Also resets the default percent thresholds for that icon
        count -- override individual ones with set_icons()."""
        ...
    def reverse_icons(self, enable: bool) -> "ConditionalFormatIconSet": ...
    def show_icons_only(self, enable: bool) -> "ConditionalFormatIconSet": ...
    def set_icons(self, icons: list[ConditionalFormatCustomIcon]) -> "ConditionalFormatIconSet":
        """List length should match the icon count for the current
        icon_type (3, 4, or 5) -- not enforced, a mismatch produces an
        inconsistent icon set in Excel rather than raising."""
        ...
    def set_multi_range(self, range: str) -> "ConditionalFormatIconSet": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatIconSet": ...
