"""Type stubs for rvgsrust_xlsxwriter._core (the PyO3-compiled extension).

Hand-written from src/lib.rs, not auto-generated. Literal types list the
exact strings each setter accepts (lower-cased internally, so case is
not significant) -- these were read out of the `match` arms in lib.rs's
parse_*() helpers, not guessed or inferred from docs.

Two accepted-value validation styles exist in the underlying code and
are preserved here rather than papered over:

- Format.set_border() and friends raise ValueError on an unrecognised
  string.
- Format.set_align(), set_vertical_align() and set_pattern() do NOT
  raise on an unrecognised string; they silently fall back to a default
  (Left / VerticalCenter / None respectively). The Literal types below
  document the accepted values, but a type checker won't catch a typo
  passed as a plain str, and neither will the library at runtime.
"""

from __future__ import annotations
from typing import Literal, Optional, Union, Any, Iterable

BorderStyle = Literal["thin", "medium", "thick", "dashed", "dotted", "double", "hair"]
DiagonalBorderType = Literal["none", "up", "down", "up_down"]
Align = Literal["left", "center", "right", "fill", "justify", "center_across", "distributed"]
VerticalAlign = Literal["top", "vcenter", "center", "bottom", "vdistributed", "distributed", "vjustify", "justify"]
Pattern = Literal[
    "none", "solid", "medium_gray", "dark_gray", "light_gray",
    "dark_horizontal", "dark_vertical", "dark_down", "dark_up",
    "dark_grid", "dark_trellis", "light_horizontal", "light_vertical",
    "light_down", "light_up", "light_grid", "light_trellis",
    "gray_125", "gray_0625",
]
DashType = Literal[
    "solid", "round_dot", "square_dot", "dash", "dash_dot",
    "long_dash", "long_dash_dot", "long_dash_dot_dot",
]
ChartType = Literal[
    "area", "area_stacked", "area_percent_stacked",
    "bar", "bar_stacked", "bar_percent_stacked",
    "column", "column_stacked", "column_percent_stacked",
    "doughnut", "line", "line_stacked", "line_percent_stacked",
    "pie", "radar", "radar_with_markers", "radar_filled",
    "scatter", "scatter_straight", "scatter_straight_with_markers",
    "scatter_smooth", "scatter_smooth_with_markers", "stock",
]
MarkerType = Literal[
    "square", "diamond", "triangle", "x", "star",
    "short_dash", "long_dash", "circle", "plus_sign",
]
TrendlineType = Literal[
    "none", "linear", "exponential", "logarithmic",
    "power", "polynomial", "moving_average",
]
SparklineType = Literal["line", "column", "win_lose", "win_loss"]
LabelPosition = Literal[
    "default", "center", "right", "left", "above", "below",
    "inside_base", "inside_end", "outside_end", "best_fit",
]
LegendPosition = Literal["right", "left", "top", "bottom", "top_right"]
EmptyCells = Literal["gaps", "zero", "connected"]
BarDirection = Literal["context", "left_to_right", "right_to_left"]
BarAxisPosition = Literal["automatic", "midpoint", "none"]
TableStyle = str  # "none", "light1".."light21", "medium1".."medium28", "dark1".."dark11"
TableFunction = Literal[
    "none", "average", "count", "count_numbers", "max", "min",
    "sum", "stddev", "var",
]
# Union with plain str because set_total_function() treats any string
# that doesn't match one of the above (after lower-casing and stripping
# underscores) as a custom formula, rather than raising.
TableFunctionArg = Union[TableFunction, str]
CfRuleType = Literal["automatic", "lowest", "min", "highest", "max", "number", "percent", "percentile", "formula"]
CfTopRule = Literal["top", "bottom", "top_percent", "bottom_percent"]
CfTextRule = Literal["contains", "does_not_contain", "begins_with", "ends_with"]
CfDateRule = Literal[
    "yesterday", "today", "tomorrow", "last_7_days",
    "last_week", "this_week", "next_week",
    "last_month", "this_month", "next_month",
]
CfAverageRule = Literal[
    "above", "below", "equal_or_above", "equal_or_below",
    "1_std_dev_above", "2_std_dev_above", "3_std_dev_above",
    "1_std_dev_below", "2_std_dev_below", "3_std_dev_below",
]

class Format:
    """Chainable cell format. Every setter returns self."""
    def set_bold(self) -> "Format": ...
    def set_italic(self) -> "Format": ...
    def set_underline(self) -> "Format": ...
    def set_font_strikethrough(self) -> "Format": ...
    def set_font_name(self, name: str) -> "Format": ...
    def set_font_size(self, size: float) -> "Format": ...
    def set_font_color(self, color: str) -> "Format": ...
    def set_background_color(self, color: str) -> "Format": ...
    def set_foreground_color(self, color: str) -> "Format": ...
    def set_pattern(self, pattern: Pattern) -> "Format":
        """Unrecognised strings silently fall back to 'none' -- no exception."""
        ...
    def set_border(self, border: BorderStyle) -> "Format":
        """Applies to all four sides. Raises ValueError if unrecognised."""
        ...
    def set_border_color(self, color: str) -> "Format": ...
    def set_top_border(self, border: BorderStyle) -> "Format": ...
    def set_bottom_border(self, border: BorderStyle) -> "Format": ...
    def set_left_border(self, border: BorderStyle) -> "Format": ...
    def set_right_border(self, border: BorderStyle) -> "Format": ...
    def set_border_top_color(self, color: str) -> "Format": ...
    def set_border_bottom_color(self, color: str) -> "Format": ...
    def set_border_left_color(self, color: str) -> "Format": ...
    def set_border_right_color(self, color: str) -> "Format": ...
    def set_border_diagonal(self, border: BorderStyle) -> "Format": ...
    def set_border_diagonal_color(self, color: str) -> "Format": ...
    def set_border_diagonal_type(self, border_type: DiagonalBorderType) -> "Format": ...
    def set_align(self, align: Align) -> "Format":
        """Unrecognised strings silently fall back to 'left' -- no exception."""
        ...
    def set_vertical_align(self, align: VerticalAlign) -> "Format":
        """Unrecognised strings silently fall back to 'vcenter' -- no exception."""
        ...
    def set_text_wrap(self) -> "Format": ...
    def set_rotation(self, rotation: int) -> "Format": ...
    def set_indent(self, indent: int) -> "Format": ...
    def set_shrink(self) -> "Format": ...
    def set_num_format(self, format: str) -> "Format": ...
    def set_locked(self) -> "Format": ...
    def set_unlocked(self) -> "Format": ...
    def set_hidden(self) -> "Format": ...

class Workbook:
    """Workbook with context manager support.

    Wraps the core Rust-backed Workbook to add __enter__ / __exit__.
    """
    path: Optional[str]
    def __init__(self, path: Optional[str] = None) -> None: ...
    def __enter__(self) -> "Workbook": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def add_worksheet(self, name: Optional[str] = None, constant_memory: bool = False) -> "Worksheet": ...
    def add_format(self) -> Format: ...
    def define_name(self, name: str, formula: str) -> None: ...
    def set_properties(
        self,
        title: Optional[str] = None,
        author: Optional[str] = None,
        subject: Optional[str] = None,
        keywords: Optional[str] = None,
        comments: Optional[str] = None,
    ) -> None: ...
    def close(self, path: Optional[str] = None) -> None:
        """Save and close. Uses the constructor path when `path` is omitted."""
        ...

class Worksheet:
    def write(self, row: int, col: int, value: Any, format: Optional[Format] = None) -> None: ...
    def write_row(self, row: int, col: int, values: Iterable[Any], format: Optional[Format] = None) -> None: ...
    def write_column(self, row: int, col: int, values: Iterable[Any], format: Optional[Format] = None) -> None: ...
    def write_rows(
        self, start_row: int, start_col: int, rows: Iterable[Iterable[Any]],
        format: Optional[Format] = None, header_format: Optional[Format] = None,
        write_header: bool = False,
    ) -> None: ...
    def write_records(
        self, start_row: int, start_col: int, records: Iterable[dict],
        headers: Optional[list[str]] = None, format: Optional[Format] = None,
        header_format: Optional[Format] = None, write_header: bool = True,
    ) -> None: ...
    def write_dataframe(
        self, start_row: int, start_col: int, data: Any,
        header_format: Optional[Format] = None, write_header: bool = True,
        column_formats: Optional[dict[str, Format]] = None,
    ) -> None:
        """Zero-copy Arrow path. `data` must expose __arrow_c_stream__
        (pandas 2.x+, polars via .to_arrow(), pyarrow.Table/RecordBatchReader).

        column_formats merges a per-column format into every cell as
        it's written, keyed by column name. This is a true per-cell
        merge, not a column-scoped format applied afterward: a border
        given here survives on a date/datetime column alongside that
        column's own date number format, because both land in the same
        cellXf rather than the column-level format losing to the cell's
        own format under OOXML precedence. Raises ValueError if a key
        doesn't match any column name, before any row is written.
        """
        ...
    def write_formula(self, row: int, col: int, formula: str, format: Optional[Format] = None) -> None: ...
    def write_url(
        self, row: int, col: int, url: str, format: Optional[Format] = None,
        text: Optional[str] = None, tip: Optional[str] = None,
    ) -> None: ...
    def write_date(self, row: int, col: int, year: int, month: int, day: int, format: Optional[Format] = None) -> None: ...
    def write_date_py(self, row: int, col: int, date: Any, format: Optional[Format] = None) -> None: ...
    def write_datetime(
        self, row: int, col: int, year: int, month: int, day: int,
        hour: int = 0, min: int = 0, sec: int = 0, format: Optional[Format] = None,
    ) -> None: ...
    def write_datetime_py(self, row: int, col: int, dt: Any, format: Optional[Format] = None) -> None: ...
    def write_rich_string(self, row: int, col: int, parts: list, format: Optional[Format] = None) -> None: ...
    def merge_range(self, first_row: int, first_col: int, last_row: int, last_col: int, value: Any, format: Optional[Format] = None) -> None: ...
    def insert_image(self, row: int, col: int, image_path: str) -> None: ...
    def insert_chart(self, row: int, col: int, chart: "Chart", x_offset: int = 0, y_offset: int = 0) -> None: ...
    def add_table(self, first_row: int, first_col: int, last_row: int, last_col: int, table: "Table") -> None: ...
    def add_conditional_format(self, first_row: int, first_col: int, last_row: int, last_col: int, cf: Any) -> None: ...
    def add_sparkline(self, row: int, col: int, sparkline: "Sparkline") -> None: ...
    def add_sparkline_group(self, first_row: int, first_col: int, last_row: int, last_col: int, sparkline: "Sparkline") -> None: ...
    def set_column_width(self, col: int, width: float) -> None: ...
    def set_column_format(self, col: int, format: Format) -> None: ...
    def set_column_range_format(self, first_col: int, last_col: int, format: Format) -> None: ...
    def set_row_height(self, row: int, height: float) -> None: ...
    def set_row_format(self, row: int, format: Format) -> None: ...
    def set_cell_format(self, row: int, col: int, format: Format) -> None: ...
    def set_range_format(self, first_row: int, first_col: int, last_row: int, last_col: int, format: Format) -> None: ...
    def freeze_panes(self, row: int, col: int) -> None: ...
    def autofit(self) -> None: ...
    def autofilter(self, first_row: int, first_col: int, last_row: int, last_col: int) -> None: ...
    def hide(self) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_tab_color(self, color: str) -> None: ...
    def protect(self, password: Optional[str] = None) -> None: ...
    def set_landscape(self) -> None: ...
    def set_portrait(self) -> None: ...
    def set_paper_size(self, paper_size: int) -> None: ...
    def set_page_order(self, enable: bool) -> None: ...
    def set_margins(
        self, left: float = 0.7, right: float = 0.7, top: float = 0.75,
        bottom: float = 0.75, header: float = 0.3, footer: float = 0.3,
    ) -> None: ...
    def set_print_area(self, first_row: int, first_col: int, last_row: int, last_col: int) -> None: ...
    def set_repeat_rows(self, first_row: int, last_row: int) -> None: ...
    def set_repeat_columns(self, first_col: int, last_col: int) -> None: ...
    def set_print_fit_to_pages(self, width: int, height: int) -> None: ...
    def set_print_scale(self, scale: int) -> None: ...
    def set_page_breaks(self, breaks: list[int]) -> None: ...
    def set_vertical_page_breaks(self, breaks: list[int]) -> None: ...
    def set_print_gridlines(self, enable: bool) -> None: ...
    def set_print_headings(self, enable: bool) -> None: ...
    def set_print_center_horizontally(self, enable: bool) -> None: ...
    def set_print_center_vertically(self, enable: bool) -> None: ...
    def set_print_black_and_white(self, enable: bool) -> None: ...
    def set_print_draft(self, enable: bool) -> None: ...
    def set_print_first_page_number(self, page_number: int) -> None: ...

class Table:
    def set_columns(self, columns: list["TableColumn"]) -> "Table": ...
    def set_name(self, name: str) -> "Table": ...
    def set_style(self, style: TableStyle) -> "Table": ...
    def set_total_row(self, enable: bool) -> "Table": ...
    def set_banded_rows(self, enable: bool) -> "Table": ...
    def set_banded_columns(self, enable: bool) -> "Table": ...
    def set_header_row(self, enable: bool) -> "Table": ...
    def set_first_column(self, enable: bool) -> "Table": ...
    def set_last_column(self, enable: bool) -> "Table": ...
    def set_autofilter(self, enable: bool) -> "Table": ...
    def set_alt_text(self, alt_text: str) -> "Table": ...
    def set_alt_text_title(self, title: str) -> "Table": ...
    def has_header_row(self) -> bool: ...
    def has_total_row(self) -> bool: ...

class TableColumn:
    def set_header(self, caption: str) -> "TableColumn": ...
    def set_header_format(self, format: Format) -> "TableColumn": ...
    def set_format(self, format: Format) -> "TableColumn": ...
    def set_formula(self, formula: str) -> "TableColumn": ...
    def set_total_function(self, function: TableFunctionArg) -> "TableColumn":
        """Any string not matching TableFunction is treated as a custom
        formula name rather than raising."""
        ...
    def set_total_label(self, label: str) -> "TableColumn": ...

class Sparkline:
    def set_range(self, range: str) -> "Sparkline": ...
    def set_type(self, sparkline_type: SparklineType) -> "Sparkline": ...
    def set_style(self, style: int) -> "Sparkline": ...
    def set_sparkline_color(self, color: str) -> "Sparkline": ...
    def set_high_point_color(self, color: str) -> "Sparkline": ...
    def set_low_point_color(self, color: str) -> "Sparkline": ...
    def set_first_point_color(self, color: str) -> "Sparkline": ...
    def set_last_point_color(self, color: str) -> "Sparkline": ...
    def set_negative_points_color(self, color: str) -> "Sparkline": ...
    def set_markers_color(self, color: str) -> "Sparkline": ...
    def show_high_point(self, enable: bool) -> "Sparkline": ...
    def show_low_point(self, enable: bool) -> "Sparkline": ...
    def show_first_point(self, enable: bool) -> "Sparkline": ...
    def show_last_point(self, enable: bool) -> "Sparkline": ...
    def show_negative_points(self, enable: bool) -> "Sparkline": ...
    def show_markers(self, enable: bool) -> "Sparkline": ...
    def show_axis(self, enable: bool) -> "Sparkline": ...
    def show_hidden_data(self, enable: bool) -> "Sparkline": ...
    def show_empty_cells_as(self, option: EmptyCells) -> "Sparkline": ...
    def set_line_weight(self, weight: float) -> "Sparkline": ...
    def set_custom_max(self, max: float) -> "Sparkline": ...
    def set_custom_min(self, min: float) -> "Sparkline": ...
    def set_group_max(self, enable: bool) -> "Sparkline": ...
    def set_group_min(self, enable: bool) -> "Sparkline": ...
    def set_date_range(self, range: str) -> "Sparkline": ...
    def set_right_to_left(self, enable: bool) -> "Sparkline": ...
    def set_column_order(self, enable: bool) -> "Sparkline": ...

class Chart:
    def __init__(self, chart_type: ChartType) -> None: ...
    def push_series(self, series: "ChartSeries") -> "Chart": ...
    def set_title_name(self, name: str) -> "Chart": ...
    def set_title_hidden(self) -> "Chart": ...
    def set_title_overlay(self, enable: bool) -> "Chart": ...
    def set_title_font(self, font: "ChartFont") -> "Chart": ...
    def set_title_format(self, format: "ChartFormat") -> "Chart": ...
    def set_legend_position(self, position: LegendPosition) -> "Chart": ...
    def set_legend_hidden(self) -> "Chart": ...
    def set_legend_overlay(self, enable: bool) -> "Chart": ...
    def set_legend_font(self, font: "ChartFont") -> "Chart": ...
    def set_legend_format(self, format: "ChartFormat") -> "Chart": ...
    def set_x_axis_name(self, name: str) -> "Chart": ...
    def set_y_axis_name(self, name: str) -> "Chart": ...
    def set_x_axis_min(self, min: float) -> "Chart": ...
    def set_x_axis_max(self, max: float) -> "Chart": ...
    def set_y_axis_min(self, min: float) -> "Chart": ...
    def set_y_axis_max(self, max: float) -> "Chart": ...
    def set_width(self, width: float) -> "Chart": ...
    def set_height(self, height: float) -> "Chart": ...
    def set_style(self, style: int) -> "Chart": ...
    def set_hole_size(self, hole_size: int) -> "Chart": ...
    def set_alt_text(self, alt_text: str) -> "Chart": ...
    def set_name(self, name: str) -> "Chart": ...
    def set_rotation(self, rotation: int) -> "Chart": ...
    def show_hidden_data(self) -> "Chart": ...
    def show_na_as_empty_cell(self) -> "Chart": ...
    def show_empty_cells_as(self, option: EmptyCells) -> "Chart": ...
    # set_x_axis_*/set_y_axis_* (name/min/max/major_unit/minor_unit/log_base/
    # num_format/hidden/reverse/major_gridlines/minor_gridlines/font/format;
    # date_axis/text_axis are x-only) mirror each other and are omitted here
    # for brevity -- see README.md's Charts section for the full list.

class ChartSeries:
    def set_values(self, range: str) -> "ChartSeries": ...
    def set_categories(self, range: str) -> "ChartSeries": ...
    def set_name(self, name: str) -> "ChartSeries": ...
    def set_format(self, format: "ChartFormat") -> "ChartSeries": ...
    def set_marker(self, marker: "ChartMarker") -> "ChartSeries": ...
    def set_trendline(self, trendline: "ChartTrendline") -> "ChartSeries": ...
    def set_data_label(self, data_label: "ChartDataLabel") -> "ChartSeries": ...
    def set_custom_data_labels(self, labels: list) -> "ChartSeries": ...
    def set_secondary_axis(self, enable: bool) -> "ChartSeries": ...
    def set_overlap(self, overlap: int) -> "ChartSeries": ...
    def set_gap(self, gap: int) -> "ChartSeries": ...
    def set_smooth(self, enable: bool) -> "ChartSeries": ...
    def set_invert_if_negative(self, enable: bool) -> "ChartSeries": ...
    def set_invert_if_negative_color(self, color: str) -> "ChartSeries": ...
    def set_point_colors(self, colors: list[str]) -> "ChartSeries": ...
    def delete_from_legend(self, enable: bool) -> "ChartSeries": ...

class ChartFormat:
    def set_fill_color(self, color: str) -> "ChartFormat": ...
    def set_fill_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_no_fill(self) -> "ChartFormat": ...
    def set_line_color(self, color: str) -> "ChartFormat": ...
    def set_line_width(self, width: float) -> "ChartFormat": ...
    def set_line_dash_type(self, dash_type: DashType) -> "ChartFormat": ...
    def set_line_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_line_hidden(self, enable: bool) -> "ChartFormat": ...
    def set_no_line(self) -> "ChartFormat": ...
    def set_border_color(self, color: str) -> "ChartFormat": ...
    def set_border_width(self, width: float) -> "ChartFormat": ...
    def set_border_dash_type(self, dash_type: DashType) -> "ChartFormat": ...
    def set_border_transparency(self, transparency: int) -> "ChartFormat": ...
    def set_border_hidden(self, enable: bool) -> "ChartFormat": ...
    def set_no_border(self) -> "ChartFormat": ...

class ChartFont:
    def set_bold(self) -> "ChartFont": ...
    def unset_bold(self) -> "ChartFont": ...
    def set_default_bold(self, enable: bool) -> "ChartFont": ...
    def set_italic(self) -> "ChartFont": ...
    def set_underline(self) -> "ChartFont": ...
    def set_strikethrough(self) -> "ChartFont": ...
    def set_color(self, color: str) -> "ChartFont": ...
    def set_name(self, font_name: str) -> "ChartFont": ...
    def set_size(self, font_size: float) -> "ChartFont": ...
    def set_rotation(self, rotation: int) -> "ChartFont": ...
    def set_right_to_left(self, enable: bool) -> "ChartFont": ...
    def set_pitch_family(self, family: int) -> "ChartFont": ...
    def set_character_set(self, character_set: int) -> "ChartFont": ...

class ChartMarker:
    def set_type(self, marker_type: MarkerType) -> "ChartMarker": ...
    def set_automatic(self) -> "ChartMarker": ...
    def set_none(self) -> "ChartMarker": ...
    def set_size(self, size: int) -> "ChartMarker": ...
    def set_format(self, format: ChartFormat) -> "ChartMarker": ...

class ChartTrendline:
    def set_type(self, trend_type: TrendlineType, period: int = 2) -> "ChartTrendline": ...
    def set_forward_period(self, period: float) -> "ChartTrendline": ...
    def set_backward_period(self, period: float) -> "ChartTrendline": ...
    def set_intercept(self, intercept: float) -> "ChartTrendline": ...
    def set_display_equation(self, enable: bool) -> "ChartTrendline": ...
    def set_display_r_squared(self, enable: bool) -> "ChartTrendline": ...
    def set_name(self, name: str) -> "ChartTrendline": ...
    def set_format(self, format: ChartFormat) -> "ChartTrendline": ...
    def set_label_font(self, font: ChartFont) -> "ChartTrendline": ...
    def set_label_format(self, format: ChartFormat) -> "ChartTrendline": ...
    def delete_from_legend(self, enable: bool) -> "ChartTrendline": ...

class ChartDataLabel:
    def show_value(self) -> "ChartDataLabel": ...
    def show_category_name(self) -> "ChartDataLabel": ...
    def show_series_name(self) -> "ChartDataLabel": ...
    def show_percentage(self) -> "ChartDataLabel": ...
    def show_leader_lines(self) -> "ChartDataLabel": ...
    def show_legend_key(self) -> "ChartDataLabel": ...
    def show_x_value(self) -> "ChartDataLabel": ...
    def show_y_value(self) -> "ChartDataLabel": ...
    def set_hidden(self, enable: bool) -> "ChartDataLabel": ...
    def set_position(self, position: LabelPosition) -> "ChartDataLabel": ...
    def set_num_format(self, num_format: str) -> "ChartDataLabel": ...
    def set_separator(self, separator: str) -> "ChartDataLabel": ...
    def set_value(self, value: str) -> "ChartDataLabel": ...
    def set_font(self, font: ChartFont) -> "ChartDataLabel": ...
    def set_format(self, format: ChartFormat) -> "ChartDataLabel": ...
    def set_custom(self, enable: bool) -> "ChartDataLabel": ...

class ConditionalFormatCell:
    def set_rule_greater_than(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_less_than(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_not_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_greater_than_or_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_less_than_or_equal_to(self, value: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_between(self, minimum: Union[int, float], maximum: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_rule_not_between(self, minimum: Union[int, float], maximum: Union[int, float]) -> "ConditionalFormatCell": ...
    def set_format(self, format: Format) -> "ConditionalFormatCell": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatCell": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatCell": ...

class ConditionalFormatBlank:
    def invert(self) -> "ConditionalFormatBlank": ...
    def set_format(self, format: Format) -> "ConditionalFormatBlank": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatBlank": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatBlank": ...

class ConditionalFormatDuplicate:
    def invert(self) -> "ConditionalFormatDuplicate": ...
    def set_format(self, format: Format) -> "ConditionalFormatDuplicate": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDuplicate": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDuplicate": ...

class ConditionalFormatError:
    def invert(self) -> "ConditionalFormatError": ...
    def set_format(self, format: Format) -> "ConditionalFormatError": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatError": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatError": ...

class ConditionalFormatFormula:
    def set_rule(self, formula: str) -> "ConditionalFormatFormula": ...
    def set_format(self, format: Format) -> "ConditionalFormatFormula": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatFormula": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatFormula": ...

class ConditionalFormatAverage:
    def set_rule(self, rule: CfAverageRule) -> "ConditionalFormatAverage": ...
    def set_format(self, format: Format) -> "ConditionalFormatAverage": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatAverage": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatAverage": ...

class ConditionalFormatTop:
    def set_rule(self, kind: CfTopRule, value: int) -> "ConditionalFormatTop": ...
    def set_format(self, format: Format) -> "ConditionalFormatTop": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatTop": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatTop": ...

class ConditionalFormatText:
    def set_rule(self, kind: CfTextRule, text: str) -> "ConditionalFormatText": ...
    def set_format(self, format: Format) -> "ConditionalFormatText": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatText": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatText": ...

class ConditionalFormatDate:
    def set_rule(self, rule: CfDateRule) -> "ConditionalFormatDate": ...
    def set_format(self, format: Format) -> "ConditionalFormatDate": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDate": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDate": ...

class ConditionalFormat2ColorScale:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat2ColorScale": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat2ColorScale": ...
    def set_minimum_color(self, color: str) -> "ConditionalFormat2ColorScale": ...
    def set_maximum_color(self, color: str) -> "ConditionalFormat2ColorScale": ...
    def set_multi_range(self, range: str) -> "ConditionalFormat2ColorScale": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormat2ColorScale": ...

class ConditionalFormat3ColorScale:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_midpoint(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormat3ColorScale": ...
    def set_minimum_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_midpoint_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_maximum_color(self, color: str) -> "ConditionalFormat3ColorScale": ...
    def set_multi_range(self, range: str) -> "ConditionalFormat3ColorScale": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormat3ColorScale": ...

class ConditionalFormatDataBar:
    def set_minimum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormatDataBar": ...
    def set_maximum(self, rule_type: CfRuleType, value: Union[str, float]) -> "ConditionalFormatDataBar": ...
    def set_fill_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_border_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_negative_fill_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_negative_border_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_axis_color(self, color: str) -> "ConditionalFormatDataBar": ...
    def set_axis_position(self, position: BarAxisPosition) -> "ConditionalFormatDataBar": ...
    def set_solid_fill(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_border_off(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_bar_only(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_direction(self, direction: BarDirection) -> "ConditionalFormatDataBar": ...
    def use_classic_style(self, enable: bool) -> "ConditionalFormatDataBar": ...
    def set_multi_range(self, range: str) -> "ConditionalFormatDataBar": ...
    def set_stop_if_true(self, enable: bool) -> "ConditionalFormatDataBar": ...
